In [ ]:
'''
project link: https://thecleverprogrammer.com/2022/04/12/tiktok-reviews-sentiment-analysis-using-python/
data source link: https://www.kaggle.com/datasets/shivkumarganesh/tiktok-google-play-store-review
'''

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('tiktok_google_play_reviews.csv')

C:\Users\haluk\AppData\Local\Temp\ipykernel_9900\583863838.py:1: DtypeWarning: Columns (8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('tiktok_google_play_reviews.csv')


In [3]:
df = df.sample(5000)

In [4]:
df['score']  = df['score'].astype(int)

In [5]:
df.T

65702   \
reviewId                           1a61ef2e-bc48-4e8f-bd25-f51f33194eb3   
userName                                                  Tehreem Zehra   
userImage             https://play-lh.googleusercontent.com/a-/ACNPE...   
content               The experience of mine has been good but tikto...   
score                                                                 5   
thumbsUpCount                                                         0   
reviewCreatedVersion                                             26.7.5   
at                                                  2022-11-03 11:51:55   
replyContent                                                        NaN   
repliedAt                                                           NaN   

                                                                 245656  \
reviewId                           2ee529f0-dcf0-486d-ab1f-3377c6dfdd33   
userName                                                  Sandra Sunday   
userImage             https://play-lh.googleusercontent.com/a/ALm5wu...   
content                                                 I love this app   
score                                                                 5   
thumbsUpCount                                                         0   
reviewCreatedVersion                                             24.0.3   
at                                                  2022-08-23 16:37:06   
replyContent                                                        NaN   
repliedAt                                                           NaN   

                                                                 230699  \
reviewId                           7b49792c-de62-42dc-b681-f81402f53f23   
userName                                                      Ray Babar   
userImage             https://play-lh.googleusercontent.com/a/ALm5wu...   
content               Sir dear tik tok team not coming views on my v...   
score                                                                 5   
thumbsUpCount                                                         0   
reviewCreatedVersion                                             25.8.5   
at                                                  2022-08-29 01:13:37   
replyContent                                                        NaN   
repliedAt                                                           NaN   

                                                                 95030   \
reviewId                           a11024ab-dbe4-4a94-9fc0-e2d18f283277   
userName                                                      Hamim Ami   
userImage             https://play-lh.googleusercontent.com/a/ALm5wu...   
content                                                       haguehueh   
score                                                                 5   
thumbsUpCount                                                         0   
reviewCreatedVersion                                                NaN   
at                                                  2022-10-21 05:58:17   
replyContent                                                        NaN   
repliedAt                                                           NaN   

                                                                 433224  \
reviewId                           4973aa1e-d316-44d9-8230-20feeaf30270   
userName                                              Ntomboxolo Kewuti   
userImage             https://play-lh.googleusercontent.com/a/ALm5wu...   
content                    My experience is the videos give me interest   
score                                                                 2   
thumbsUpCount                                                         0   
reviewCreatedVersion                                                NaN   
at                                                  2022-06-26 19:40:28   
replyContent                                                        NaN   
repliedAt  

In [6]:
# INITIAL DATA  MANIPULATIONs

In [7]:
# kucuk harfe donustur
df['content'] = df['content'].astype(str)
df["content"]=df["content"].str.lower()
# noktalama isaretlerini kaldirma
df["content"]=df["content"].str.replace("[^\w\s]","") 
# rakamlari kaldir
df["content"]=df["content"].str.replace("\d+","") 
# \newline ve enter\r kaldir
df["content"]=df["content"].str.replace("\n"," ").replace("\r","") 
# fazladan bosluklari azalt
df["content"]=df["content"].str.replace("  "," ")

C:\Users\haluk\AppData\Local\Temp\ipykernel_9900\1261327914.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df["content"]=df["content"].str.replace("[^\w\s]","")
C:\Users\haluk\AppData\Local\Temp\ipykernel_9900\1261327914.py:7: FutureWarning: The default value of regex will change from True to False in a future version.
  df["content"]=df["content"].str.replace("\d+","")


In [8]:
# strip out html tags
import html
def del_html(text):
   return html.unescape(text)

# Apply to multiple columns
df['content'] = df['content'].apply(del_html)

In [9]:
df = df.dropna(subset=['content'])

In [10]:
# LANGUAGE DETECTION
# There are comments in multiple languages in the comment section
# It is very difficult to simultaneously process different languages
# and apply sentiment analysis. Therefore, we filter out non-english
# comments in our analysis. 

In [11]:
# Function to detect the language of a text using langdetect
import pandas as pd
from langdetect import detect

def detect_language(text):
    try:
        
        return detect(text)
    except:
        #there are emojis also, which may not be detected as language
        return 'unknown'

# Apply the language detection function to the 'text' column
df['language'] = df['content'].apply(detect_language)
df = df[df['language'] == 'en']

In [12]:
df.T

65702   \
reviewId                           1a61ef2e-bc48-4e8f-bd25-f51f33194eb3   
userName                                                  Tehreem Zehra   
userImage             https://play-lh.googleusercontent.com/a-/ACNPE...   
content               the experience of mine has been good but tikto...   
score                                                                 5   
thumbsUpCount                                                         0   
reviewCreatedVersion                                             26.7.5   
at                                                  2022-11-03 11:51:55   
replyContent                                                        NaN   
repliedAt                                                           NaN   
language                                                             en   

                                                                 245656  \
reviewId                           2ee529f0-dcf0-486d-ab1f-3377c6dfdd33   
userName                                                  Sandra Sunday   
userImage             https://play-lh.googleusercontent.com/a/ALm5wu...   
content                                                 i love this app   
score                                                                 5   
thumbsUpCount                                                         0   
reviewCreatedVersion                                             24.0.3   
at                                                  2022-08-23 16:37:06   
replyContent                                                        NaN   
repliedAt                                                           NaN   
language                                                             en   

                                                                 230699  \
reviewId                           7b49792c-de62-42dc-b681-f81402f53f23   
userName                                                      Ray Babar   
userImage             https://play-lh.googleusercontent.com/a/ALm5wu...   
content               sir dear tik tok team not coming views on my v...   
score                                                                 5   
thumbsUpCount                                                         0   
reviewCreatedVersion                                             25.8.5   
at                                                  2022-08-29 01:13:37   
replyContent                                                        NaN   
repliedAt                                                           NaN   
language                                                             en   

                                                                 433224  \
reviewId                           4973aa1e-d316-44d9-8230-20feeaf30270   
userName                                              Ntomboxolo Kewuti   
userImage             https://play-lh.googleusercontent.com/a/ALm5wu...   
content                    my experience is the videos give me interest   
score                                                                 2   
thumbsUpCount                                                         0   
reviewCreatedVersion                                                NaN   
at                                                  2022-06-26 19:40:28   
replyContent                                                        NaN   
repliedAt                                                           NaN   
language                                                             en   

                                                                 303801  \
reviewId                           47cf20ca-20fe-437c-b7a6-00696a5b8882   
userName                                                 Jeff Humphreys   
userImage             https://play-lh.googleusercontent.com/a/ALm5wu...   
content               lost my first acc made another acc has no sear...   
score                                                                 1   
thumbsUpCou

In [13]:
# FIND ROOTS, REMOVE PREFIXES, CORRECT SPELLING MISTAKES

In [14]:
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from autocorrect import Speller
import re
from multiprocessing import Pool
import multiprocessing as mp

import concurrent.futures
from textblob import TextBlob

def find_word_roots(text):
    
    # Create a TextBlob object
    #blob = TextBlob(text)
    #text = blob.correct()
    spell = Speller(lang='en')
    # correct text
    text = spell(text)
    
    pr = PorterStemmer()
    lm = WordNetLemmatizer()
    
    # find roots
    words = text.split(" ");
    kokler = [pr.stem(word) for word in words]
    
    #remove prefixes 
    kokler_k = [];
    for kok in kokler :
        kok=spell(kok)
        #blob = TextBlob(kok)
        # Correct the text
        #kok = str(blob.correct())
        
        kokler_k.append( lm.lemmatize(kok,pos = 'v') )
        
    #remove     
    
    ret_str = "";
    for kok in kokler_k :
        ret_str = ret_str +" "+kok
        
    # remove https part
    ret_str =re.sub(r'https?\S+', '', ret_str)    
    print(ret_str)    
    return ret_str

#num_processes = mp.cpu_count()*1;
#num_processes = 1;
#with Pool(num_processes) as pool:
#    # Use the Pool's map function to apply your function to the column
#    results = pool.map(find_word_roots, df['text'])

# Add the results as a new column in your DataFrame
#df['textt'] = results


#with concurrent.futures.ProcessPoolExecutor() as executor:
#    results = list(executor.map(find_word_roots, df['text']))

df['content'] = df['content'].apply(find_word_roots)  

 the expert of mine ha be good but tiktok keep delete my video and say they be inappropri when they be not and ban my video hope tiktok fix thi issue
 i love thi app
 sir dear tik tok team not come view on my video pleas sir viral my video my id babaransari
 my expert be the video give me interest
 lose my first acc make not acc ha no search option cant view profil no way to switch from private to public just alot of screw up since last update
 very good nice app i just start use it and l have so mani like and follow a nice app rate for my age even though i be no ani more
 great app
 perfect keep up the app be user friendly and meet my need 
 it a good app but the update thing be break
 honestly thi be not good for me
 thank tik tok team tiktok be the best platform in the world
 help
 i just like people n they r very funny n they away make me laugh 
 love the mmm
 thi be a good one app and thi be a mission of the every
 i love tiktok but the new update be the worst  i think we should b

 it a very good app
 love thi app it fun
 better than facebook and you tube
 i love thi educishon app
 i enjoy the short video some make very hard happyhappi happy
 who i cant download thi appwhenev i want to download thi split show that it cant be downloadedwhypleas sell thi issue anyway i love thi app
 there be not wrong with my tick take i enjoy my video
 nat com money
 most ama and fun
 i luv thi app so much ive be addict since 
 rofingil
 not enough motion in my house for thi app
 very nice app
 pleas download hard
 it keep want me to update my tiktok and i tri and tri and doi and it just install not one
 i dont like it because he doesnt open in syria who and i open simon pro i hate thi my heart be break i swear pleas open
 it the best app in the world
 it wa great
 while tiktok be load of fun the user agreement be accept to me bear of what your give permit to with thi app read the small print in it entirety
 very entertain i can laughcri on thi app it timekil and you cant stop sc

 love it so much
 thi app very nice
 dear tiktok team double exposure effect not show my bus account pleas focus thi problem think you
 very nice pass time
 good way for me to past the time by when im bore
 interest
 i dont have to much expert with tiktok yet i be happy to give a meter opinion on tiktok later thank you pete nez
 when it install it take all day
 it so east to swine 
 hello my follow be decrease from to pleas help me
 touch density not work button dont pick up me press s ultra s mess up word eras other word not load properly as well
 love the video but way too mani people fish and tiktok take the word of troll they suspend and ban people without just cap
 dear tiktok team i have be upload video on tiktok accord to the analyst but my video arent reach forget and i be also not gain follow as per my artwork on tiktok it very disappoint for me so kindly review my account and fix the problem as soon as possible thank you
 very thank to the creator and of thi for give everyone

 pleas dear tiktok team my all video view and viral
 most of tiktok video do make me need tissue cup i laugh so hard til i cri laugh
 get ban for no reason wish i could give it star tri to figure out who i wa but doesnt say who
 thi be viral app
 if you want your brain push download thi thi app be so far out of the scope of be for kid that it ticket chinese tiktok show not but edu and work relay mater western tiktok show you women breast and people die children put themself in dangersexu post etc it fill to the rim with self center weird paedophile disable people china be spi on you your destroy your brain boycott thi self destruct app
 name edit issue long day after i think title team set thi pleas
 the content be very elev to my life and mot uplift
 fun way to meet new people the major thing i dont like be when you find a video you like and want to repost from you page and tic tok either take the video down or they mute the sound track it doesnt make sens how the video go against the

 good app
 thi be a very good and nice app
 latest update ruin it i update it to see the cool new feature and now the app wont open
 very very good i love it soo much but my count be soon slow i be use tiktok a long time but tiktok dot give me fame thi ma gmail n title dkrajputplz viral my video
 it overall super good great time killer away new video and good content
 tick take be cool
 so mani problem where do i begin
 good app
 i love thi app
 it a great app
 pleas aap mere account ko viral kar do pleas for you
 thi tiktok app should be ban in nepal as there be mani content creator who be make good and nice video but some be do very much they be put node violate thing in tiktok and mani thing about other country and own country so it should be ban or look at the tiktok of nepal
 i get so much follow on tiktok
 great app but when a tiktok add be play it make me want to delete tiktok
 it actual a good app now
 love the new video edit tool
 cool
 better than facebook hook
 nice app plea

 i love thi appexcept of cours for the occasion regard that hate the constitute and doesnt want to be free
 common tate w
 i use to like tiktok but the past few month it ha be glitch and th i have to delete it but i might download it again if all the glitch be fix
 good app
 bro i get ban for no reason and now i cant even make one until tt give me my account back
 hi i really do love the app but can you pleas make it to where the app support the full k feature on my lg v think g so i can upload my highest quality video pleas and thank you
 very pleasant to be part of tik tok because somehow i find thing that ii really relay to so yeah 
 unfree my account
 it ha the video i like to see
 the app be very beauty
 it be mostly fun
 forget
 thi app be not increase viewer so thi app be not best
 i lobe ot not van top thi
 be a vari good for pass time
 it wa awesome i really enjoy it and be sti enjoy the apl
 good it just i all way get ban
 wow that be very omg
 it very ama away
 i think best 

 great app
 im also know you follow me only ok
 ill give star if you let us switch country and watch that country content im tire of see bring content of my country and away need vpn to see other country content
 well it a good app it awesome but my problem be i have like and follow but it not approve yet 
 when i open thi app and use after sometime automata close itself
 that great app for social life reality of world stat of real life problem of people that a great social media
 just love thi app
 how you can come over and bike and do a lot of thing and stuff 
 good app 
 it thi good app
 it be most expense than other app
 it inch algorithm be nice to mei guess i should post more
 good app
 very bad app
 dear tiktok administer i have follow and i be post my best video but the view be come not more at all and non of my video go viral plz fix the problem thank u 
 okay i give it a three but hear me out so i have tiktok for a heck of a time i love my real follow but there be a problem t

 thi app be great even my video be not get like but it all filter and effect be great
 there be thing that have really scare me
 i like the tick but my tick id be just furious the tick be not viral i tick it so hard it doesnt go viral pleas make my tick id viral sir
 thi app be so cool and i like thi app
 good app tiktok account
 thi be the only social media app that entertain me nowadays
 stun way to find fun etc
 i like tiktok app best and safe app ever end of the word app
 hi and my problem be daily routine my tiktok like miss so pleas solute my problem urgent
 thi app be extreme addict
 bad common in thi apply
 who thi app be not avail for iran
 thi be a really great app but all of a sudden when my phone do not have enough storage tiktok keep on tell me to update it so after success attempt to tri to update it it do not work so i decide to delete tiktok then download it but it not work pleas can you find a way to resolve thi issue because im not will to download tiktok lite
 love t

 nice very good
 forget
 it ama but im lead it
 very impress 
 cool and fun
 wa full ban without ani warn or any about what i do lose all my video all my save video every wa not abl to appeal or do any
 issue with every video not be upload issue with i add everyone to them not be on my list or no one be see my video not sure if i be shadow ban or what but it be mess up
 good app best of luck
 it a good
 you have a former manga whose ish and master former they future end well in the city of our live in a way we have to do with our society to make it happen in a time where the destruct be a matter for our society and we will not be abl it and the rest be the only god we will have the right of god who will not have to be give a matter of faith in the bill or to make the destruct the destruct and destruct be not have a god and we have no idea that the destruct be the destruct
 it so fun to make video and watch them
 awesome expert with thi
 i have fun with thi app
 i think it pretty east a

 thing you
 some people be della toxic but it overall very nice
 who doe not live in my tiktok
 good app
 it be fun
 tiktok be very very very very very dirty app not a video go to forget people not a like video
 it be good to sit s f watch tico
 good app tax tik tok company kkk
 channel suspend ngbadsha
 i advise everyone to download the program on 
 shadowbot for no reason who even put effort in and make content on thi app when ppl just screenshot a tweet and post it for k like and that content get push by the algorithm
 im use tiktok from year it be good app for entertain and enjoy entertain in video content in which we can chang our lifestyle habit or mani i like it ssooooooooooo much
 hi tiktok time my account viral video call
 great app
 the be more fun in thi app
 it an ama app that allow you to be in contact with the world
 thi be a good and a fun app
 sir pleas like and view pleas i be your old member
 thi app be ama it help to feel good
 artist
 ama app but the wallpaper thing

 very nice platform
 tiktok be the best app that have be make by the way
 tik tok team liz viral my account
 cool
 ooh i really love thi appbecuz it make you know thing and place in the world
 bring and take up too much storage
 very bad i dont want to see those kind of video i continue give not interest but tiktok keep show that kind of video for thi reason my friend also very angry he final install tiktok app
 breathtak
 good comedy and social app
 excel i love it i love it i have follow and i love it 
 your video ha be mute your video ha be mute because it contain music that exec the allow maximum draw wa not
 the best app
 i love the app it genuine fun and ive meet a lot of people on it but it refs to let me appeal a white screen show up when i tri to open the appeal page
 funny stuff on there pl a lot of really interest video
 harm track
 thi app be awesome i fell very pleasure joy to use thi app
 tiktok wont let me open my account cap it say i need to install update but there be 

 very very very nice and enjoy wonder
 good very inform and interest
 just not app cater to iphone the app ha too mani frequent update for extreme small chang and eat up a lot of your data current ha take up over a gigabit of mine message be buggy and load at the start of the chat not the most recent message video process for over hour despite there be not wrong with them you can tell not every video get the privilege of be active on the fp which should be chang samsung get bare ani good filter fix it thank
 love it badly
 i use to like tiktok but i rare use it anymore since i wa shadow ban for refs to pay for my like follow and view now my video hardly get ani view anymore sorry tiktok but i wont be for to pay i save all my video so delete my account if you want
 great app love it
 i cant link my account to social media
 plz remove the caucus video
 too much good app
 thi be a real star expert love it like mad
 great app love it
 that good thing about me
 it go on very good
 what happ

 grand rai the great work with the help jeniresen in the world of people that have be abl to make sure your own homegrown
 so interest and smooth
 ama funny video app great diy project
 just cool with it
 thi be the worst app ive ever use they let one of their employ to break my account she take my account her name be garcia stella i complain to tiktok they have do absolute not to help me or fire her she should be charg with a cyber intact by the fbi until tiktok take action against garcia i will no longer use that app sig reverend eagle
 plz unfree my account and viral my every video i love tiktok
 east to use
 have follow
 it really good app
 can you pleas give your user the option to remove or turn off the double tap again to exit feature i like thi platform a lot but i dont like that it make me feel trap i never accident close the app if that be what your tri to inline with thi feature when i want to close the app i actual want to close the app i dont think it health for kid which 

 tiktok team account for you par hay
 very nice app
 i love thi app so much
 cool
 it an ama app i have fun overtime i on it to see more video
 i over love thi app
 video cant pass or restart thank for fix thi problem
 interest for you video account warn be come ani solute
 i love it be fun
 east to use
 it so nice ap
 viral my account plz tiktok
 thi app so fun 
 good bad silly say but i it cool though
 good app top
 absolute oper do not download
 wow it soo ama
 all good i love thi app
 very good and fun
 put me know
 it so stupid of my account get ban and of them have follow which be hard to earn back fix your company
 im give thi a one star rate because for absolute no reason should we use the kilallmen which ha view on tiktok create hate speech against men which be probably the reason who tiktok be ban in a lot of country  my point be tiktok need to fix their stuff with tiktok user hack ban account and delete my account along with it so pl fix these two problem for now i install t

 there wa an option that allow you to hide all the thing that be on the screen to watch better the videosclear frame i think it as call but not it isnt avail anymore so disappoint 
 who my account warn 
 tiktok be east to use i away see happy people on there
 best appear social
 fun to be on
 great love take the people great content just love it
 i just love thi app there so mani thing to explore and learn you can also make video for money i recommend thi app
 great app love all it content
 the app i have ever see
 tiktok be a great app but the model system be a joke it say no violate when some bad be report
 really enjoy use thi app
 thi be perfect 
 fun and exit
  out of 
 dear tiktok team pleas unfree my account pleas i like tiktok but dont forget my video
 when i tri to see my tag or comment in the active section it doesnt appear i have to constantly lead and open the app to see notify
 your racist in how you favor right polite
 i think it be a good app but id how it work
 ill give

 tik tok ha get work over time because just thi more tri message in a live chat and my message weren go through and i wasnt say any about so pleas fix thi or update the app
 it also loser student
 tiktok pleas boost my account
 he day shop data well well
 i love thi app that all i can say tri it out i promise you will love it
 i really love it
 the best app i have see
 terrible i get ban for appear be under the age of i be but it ban me howe i tri to add a new account but it didnt let me i install it and in stall it again but i ad a birthday and it say im not eli thi be my th time tri and still doesnt work fix your app tiktok 
 good app
 i really enjoy thi app it more addict than drug a good one for recon addict i forget all about my beer i have
 i feel so happy when use thi app
 very good for entertain us
 i hate thi appbecaus there lot of bad content inside of thi appwhich be not safe i would never recommend it to anyone
 my tiktok account not work not open reason
 good app
 thi app


 in my tiktok ac no option wo can view my profil
 the best app ever
 it away make me relaunch the app
 nice here
 very good entertain and east app
 support me i will support you key___edit
 good app
 tax for watch 
 here you can get creative in mani way show other your talent 
 great expert good app
 thi be the best app for time stage
 ive have thi app for long and all off a sudden while you watch and scroll through video the video ive watch and like already be show up and that never use to happen
 fun inform unique in that you can see the vastly differ culture and people worldwide ama video from liter everywhere on earth place i will never be abl to see in person can be see here liter everywhere as well as open dialog with anyone online anywhere aaa
 it be great use 
 greatest it take much data but it be wonder 
 away common guideline
 good app and promote your video and very so hope app
 it great
 sir my follow but not good view my video way and my video only analyst person show way 

In [15]:
# Remove STOP words
# Taken from Amazon 
import re
import nltk

from nltk import word_tokenize, pos_tag
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import sent_tokenize
from nltk.corpus import wordnet
from nltk.corpus import stopwords

#import nltk resources
resources = ["wordnet", "stopwords", "punkt", \
             "averaged_perceptron_tagger", "maxent_treebank_pos_tagger"]

for resource in resources:
    try:
        nltk.data.find("tokenizers/" + resource)
    except LookupError:
        nltk.download(resource)

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\haluk\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\haluk\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\haluk\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_treebank_pos_tagger to
[nltk_data]     C:\Users\haluk\AppData\Roaming\nltk_data...
[nltk_data]   Package maxent_treebank_pos_tagger is already up-to-
[nltk_data]       date!


In [16]:
from nltk.corpus import stopwords
from nltk.tokenize import TreebankWordTokenizer

stop_words = stopwords.words("english")

stop_words = [word.replace("\'", "") for word in stop_words]

In [17]:
# remove stopwords

import six
import time

i = 0;
nan_index = []
text_wo_sw = []
for text in df['content']:
    
    ret_str ="";
    if isinstance(text, six.string_types):
    
        splitted_text = text.split(" ");
        for word in splitted_text:
            #print(word)

            if len(word)>0 and isinstance(word, six.string_types):
                if word not in stop_words:
                    ret_str = ret_str +" "+word
                        
            #else :
                #print(word)
                #print('not string')
    else :
        #print(i) 
        #print(text)
        nan_index.append(i)
        #print('not a string unfortunately')
    
    text_wo_sw.append(ret_str)
    i=i+1;    
df['content'] =  text_wo_sw 
df.drop(df.index[nan_index], inplace=True)

In [18]:
df['content']

65702      expert mine ha good tiktok keep delete video ...
245656                                         love thi app
230699     sir dear tik tok team come view video pleas s...
433224                           expert video give interest
303801     lose first acc make acc ha search option cant...
                                ...                        
136395         love tiktok sometime pair airport pick sound
18247      good content reason cant share ani friend tik...
68738                                       cool since come
250470     bad open app doe open open open google come l...
172898                                             nice app
Name: content, Length: 2244, dtype: object

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

vect =  CountVectorizer()



In [20]:
df.loc[df['score'] == 3,"sentiment"]= 0
df.loc[df['score'] < 3,"sentiment"]= -1
df.loc[df['score'] > 3,"sentiment"]= 1

In [21]:
x = df['content']
y = df['sentiment']

In [22]:
x = vect.fit_transform(x)

In [23]:
x.shape, y.shape

((2244, 2062), (2244,))

In [24]:
def algo_test(x,y):
    
    import numpy as np

    from scipy import stats
    import matplotlib.pyplot as plt
    %matplotlib inline 
    import seaborn as sns


    from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
    from sklearn.linear_model import LinearRegression, ElasticNet, Ridge, Lasso
    from sklearn.tree import ExtraTreeClassifier
    from sklearn.ensemble import GradientBoostingRegressor
    from xgboost import XGBRegressor 

    from sklearn.model_selection import train_test_split

    from sklearn.model_selection import train_test_split
    from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
    from sklearn.naive_bayes import GaussianNB
    from sklearn.naive_bayes import BernoulliNB
    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.linear_model import LogisticRegression
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.svm import SVC
    from sklearn.linear_model import SGDClassifier

    import warnings
    warnings.filterwarnings('ignore')
    #plt.style.use('')

    
    G = GaussianNB()
    B = BernoulliNB()
    K = KNeighborsClassifier()
    L = LogisticRegression()
    D = DecisionTreeClassifier()
    S = SVC()
    SGD = SGDClassifier()

    x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state = 13)
    
    #algos = [G,B,K,L,D,S]
    algos = [G,B,K,L,D, SGD]
    
    #algo_names = [ "Gaussian", "Bernoulli", "K-Neighbors", "Logistic Regression", "Decision Tree","SVC" ]
    algo_names = [ "Gaussian", "Bernoulli", "K-Neighbors", "Logistic Regression", "Decision Tree", \
                  'Stochastic Gradient Descent' ]
    
    ASC = [];
    
    result =  result = pd.DataFrame(columns =['Accuracy_Score'], index = algo_names)
    
    i = 0;
    for algo in algos :
        
        algo.fit(x_train,y_train)
        print (accuracy_score(  y_test, algo.predict(x_test) ))
        ASC.append(  accuracy_score(  y_test, algo.predict(x_test) ) )
        
        print( "Confusion matrix: ",format(algo_names[i]) )
        i = i+1;
        print ( confusion_matrix(algo.predict(x_test),y_test) )
        
        #algo.fit(x,y)
        #print (accuracy_score(  y, algo.predict(x) ))
        #ASC.append(  accuracy_score(  y, algo.predict(x) ) )
    
    
    result.Accuracy_Score = ASC;

    return result.sort_values('Accuracy_Score', ascending=False)

In [25]:
algo_test(x.toarray(),y)

0.24721603563474387
Confusion matrix:  Gaussian
[[ 47   8  83]
 [ 40   9 196]
 [ 10   1  55]]
0.755011135857461
Confusion matrix:  Bernoulli
[[ 27   7  17]
 [  3   0   5]
 [ 67  11 312]]
0.7616926503340757
Confusion matrix:  K-Neighbors
[[ 15   3   7]
 [  1   0   0]
 [ 81  15 327]]
0.779510022271715
Confusion matrix:  Logistic Regression
[[ 37   6  18]
 [  3   1   4]
 [ 57  11 312]]
0.7282850779510023
Confusion matrix:  Decision Tree
[[ 44   6  38]
 [  7   0  13]
 [ 46  12 283]]
0.7461024498886414
Confusion matrix:  Stochastic Gradient Descent
[[ 39   6  34]
 [  8   2   6]
 [ 50  10 294]]


Accuracy_Score
Logistic Regression                0.779510
K-Neighbors                        0.761693
Bernoulli                          0.755011
Stochastic Gradient Descent        0.746102
Decision Tree                      0.728285
Gaussian                           0.247216